name: build and test feature branch
on:
  push:
    branches:
      - feature/*
jobs:
  build-feature:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: pull and checkout from git repository
        run: |
          echo "pulling and checking out from git repository"

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install npm packages
        run: npm ci

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Run tests
        run: |
          ng test
          echo "run tests on Angular app"

      - name: Build Angular app
        run: |
          ng build --prod
          echo "build Angular app"
